import Decimal from 'decimal.js';
import { EarnEventClaimType } from './EarnEventClaimType.type';
export type EarnEvent = {
    id: string;
    alias: string;
    eventStartAt: Date;
    eventEndAt: Date;
    claimStartAt: Date;
    claimEndAt: Date;
    iconUrl: string;
    title: object;
    subTitle: object;
    detailPageHtml: object;
    pointArr: object;
    pointIconUrl: string;
    eventActionButtonTitle: object | null;
    allowTimeRange: object | null;
    eventActionScheme: string | null;
    connectionDeepLink: string | null;
    currencyId: string;
    subCurrencyId: string | null;
    subCurrencyReward: Decimal | null;
    maxReward: Decimal;
    lowerLimitReward: Decimal | null;
    maxParticipationUserCount: number | null;
    rewardPerValue: Decimal | null;
    claimType: EarnEventClaimType;
    appId: string | null;
    description: string | null;
    createdAt: Date;
    updatedAt: Date;
    isAllowParticipationInClaim: boolean;
    data: object | null;
};
